#ifndef CMD_SRV_H
#define CMD_SRV_H

#include <stdlib.h>
#include <mqueue.h>

#define _F_	__FILE__
#define _FU_	__FUNCTION__
#define _L_	__LINE__

#define IPC_QUEUE_NAME "/ipc_dispatch"

#define MID_P2P 1
#define MID_RMM 2
#define MID_CLOUD 4
#define MID_DISPATCH 4
#define MID_RCD 0x10

typedef enum {
    DISPATCH_SET_TIME = 0x71,
    DISPATCH_SET_BIND_FAIL = 0x73,
    DISPATCH_SET_POWER_ON = 0x74,
    DISPATCH_SET_POWER_OFF = 0x75,
    DISPATCH_SET_LIGHT_ON = 0x76,
    DISPATCH_SET_LIGHT_OFF = 0x77,
    DISPATCH_SET_MOTION_RCD = 0x78,
    DISPATCH_SET_ALWAYS_RCD = 0x79,
    DISPATCH_SET_MIRROR_ON = 0x7a,
    DISPATCH_SET_MIRROR_OFF = 0x7b,
    DISPATCH_MOTION_DETECT_START = 0x7c,
    DISPATCH_MOTION_DETECT_STOP = 0x7d,
    DISPATCH_SET_TNP_INIT_STATUS = 0x7f,
    DISPATCH_SET_TNP_WORK_MODE = 0x80,
    DISPATCH_SET_SD_FORMAT = 0x85,
    DISPATCH_SET_DEBUG_MODE = 0x86,
    DISPATCH_SET_VIDEO_BACKUP_STATE = 0x87,
    DISPATCH_SET_BAN_DEVICE = 0x88,
    DISPATCH_SYNC_INFO_FROM_SERVER = 0x89,
    DISPATCH_FINISH_SYNC_INFO_FROM_SERVER = 0x8a,
    DISPATCH_SET_CLOUD_STORAGE_ON = 0x8b,
    DISPATCH_SET_CLOUD_STORAGE_OFF = 0x8c,
    DISPATCH_SET_REGION = 0x8d,
    DISPATCH_SET_TZ_OFFSET = 0x8e,
    DISPATCH_SET_PWD_USED_CNT = 0x8f,
    DISPATCH_SET_PWD_SYNC_SERVER = 0x90,
    DISPATCH_SET_OTA_STATE = 0x91,
    DISPATCH_SET_PANORAMA_CAPTURE_STATE = 0x92,
    DISPATCH_SET_PANORAMA_CAPTURE_COUNT = 0x93,
    DISPATCH_SET_CLOUD_STORAGE_MODE_MOTION_DETECT = 0x94,
    DISPATCH_SET_CLOUD_STORAGE_MODE_ALL_DAY = 0x95,
    DISPATCH_SAVE_API_SERVER = 0x96,
    DISPATCH_CLEAR_API_SERVER = 0x97,
    DISPATCH_SET_BIND_TIMEOUT = 0x98,
    DISPATCH_SPEAK_WRONG_DEVICE = 0x99,
    DISPATCH_SET_LAPSE_VIDEO = 0x9a,
    DISPATCH_SET_LAPSE_VIDEO_MODIFY = 0x9b,
    DISPATCH_P2P_CONNECTTED = 0xe1,
    DISPATCH_P2P_DISCONNECTTED = 0xe2,
    DISPATCH_P2P_VIEWING = 0xe3,
    DISPATCH_P2P_STOP_VIEWING = 0xe4,
    DISPATCH_P2P_CLR_VIEWING = 0xe5,
    DISPATCH_MOTION_TRACKING_DETECT_START = 0xe6,
    DISPATCH_BABYCRY_OCCUR = 0xea,
    DISPATCH_BABYCRY_CLEAR = 0xeb,
    DISPATCH_SET_SCHEDULE_POWER = 0xec,
    DISPATCH_HUMAN_DETECT_START = 0xed,
    DISPATCH_ABNORMAL_SOUND_OCCUR = 0xee,
    DISPATCH_ABNORMAL_SOUND_CLEAR = 0xef,
    DISPATCH_CLOUD_PIC_INDEX_OCCUR = 0xf0,
    DISPATCH_CLOUD_PIC_INDEX_CLEAR = 0xf1,
    DISPATCH_CLOUD_PIC_SET_INTERVAL = 0xf2,
    DISPATCH_SET_CLOUD_IMAGE_ON = 0xf3,
    DISPATCH_SET_CLOUD_IMAGE_OFF = 0xf4,
    DISPATCH_START_RECORDE = 0Xf5,
    DISPATCH_STOP_RECORDE = 0Xf6,
    DISPATCH_FACE_DETECT_START = 0xf7,
    RMM_SPEAK_SUCCESS = 0x1000,
    RMM_SPEAK_RESET = 0x1001,
    RMM_SPEAK_WAIT = 0x1002,
    RMM_SPEAK_PWD_WRONG = 0x1003,
    RMM_SPEAK_CONNECTTING = 0x1004,
    RMM_SPEAK_SCAN_OK = 0x1005,
    RMM_SPEAK_WIFI_CONNECTTED = 0x1006,
    RMM_START_CAPTURE = 0x1007,
    RMM_START_WELCOME = 0x1008,
    RMM_SPEAK_BINDFAIL = 0x1009,
    RMM_SPEAK_DOWNLOADING = 0x100a,
    RMM_SPEAK_UPDATING = 0x100b,
    RMM_SPEAK_DOWNLOAD_FAIL = 0x100c,
    RMM_SPEAK_BAN_DEVICE = 0x100d,
    RMM_APP_MODE_EARPHONE = 0x1021,
    RMM_APP_MODE_SPKER = 0x1022,
    RMM_SET_MOTION_DETECT = 0x1023,
    RMM_SET_DAY_NIGHT_MODE = 0x1024,
    RMM_SET_MOTION_SENSITIVITY = 0x1027,
    RMM_SET_LDC = 0x1028,
    RMM_SET_BABY_CRY = 0x1029,
    RMM_SET_MIC_VOLUME = 0x102a,
    RMM_START_PANORAMA_CAPTURE = 0x102b,
    RMM_ABORT_PANORAMA_CAPTURE = 0x102c,
    RMM_SPEAK_WRONG_DEVICE = 0x1031,
    RMM_SET_ENCODE_MODE = 0x1032,
    RMM_SET_HIGH_RESOLUTION = 0x1033,
    RNN_VC_START_RECORD = 0x1034,
    RMM_VC_STOP_RECORD = 0x1035,
    RMM_SET_LAPSE_FRAMERATE = 0x1036,
    RMM_SET_LAPSE_FORCE_IDR = 0x1037,
    RMM_APP_AUDIO_MODE_SIMPLEX = 0x1038,
    RMM_APP_AUDIO_MODE_DUPLEX = 0x1039,
    RMM_SET_ABNORMAL_SOUND = 0x103a,
    RMM_SET_ABNORMAL_SOUND_SENSITIVITY = 0x103b,
    RMM_SET_HUMAN_MOTION = 0x103c,
    RMM_SET_FACE_MOTION = 0x103d,
    RCD_START_SHORT_VIDEO = 0x2000,
    RCD_START_SHORT_VIDEO_10S = 0x2001,
    RCD_START_VOICECMD_VIDEO = 0x2002,
    RCD_START_SHORT_FACE_VIDEO = 0x2003,
    RCD_START_SHORT_HUMAN_VIDEO = 0x2004,
    DISPATCH_SET_VIEWPOINT_TRACE = 0x3002,
    DISPATCH_SET_VOICE_CTRL = 0x3003,
    DISPATCH_P2P_PTZ_PRESET_ADD = 0x4000,
    DISPATCH_P2P_PTZ_PRESET_DEL = 0x4001,
    DISPATCH_P2P_PTZ_SET_CRUISE_STAY_TIME = 0x4003,
    DISPATCH_P2P_PTZ_CRUISE_START = 0x4004,
    DISPATCH_P2P_PTZ_CRUISE_STOP = 0x4005,
    DISPATCH_P2P_PTZ_SET_CURISE_PERIOD = 0x400a,
    DISPATCH_P2P_PTZ_SET_MOTION_TRACK = 0x400b,
    BABYCRY_START_MSG = 0x6002,
    ABNORMAL_SOUND_START_MSG = 0x6004,
    CLOUD_DEBUG_ALARM = 0x6006
} MSG_TYPE;

typedef struct
{
    int dstMid;
    int srcMid;
    short mainOp;
    short subOp;
    int msgLength;
} mqueue_msg_header_t;

void dump_string(char *source_file, const char *func, int line, char *text, ...);
int cloud_send_msg(mqd_t mqfd, MSG_TYPE msg_type, char *payload, int payload_len);
int cloud_send_msg_ex(mqd_t mqfd, MSG_TYPE msg_type, short sub, char *payload, int payload_len);

#endif
