#!/bin/sh
if [ -d "/tmp/sd/yi-hack-v5" ]; then
    /tmp/sd/yi-hack-v5/script/system.sh
else
        sleep 2
        ./home/app/mp4record &
        ./home/app/cloud &
        ./home/app/p2p_tnp &
        ./home/app/oss &
        ./home/app/watch_process &
        tcpsvd -vE 0.0.0.0 21 ftpd -w &
        telnetd &
fi
