#!/bin/sh

ulimit -s 1024
export LD_LIBRARY_PATH=/home/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/tmp/sd/yi-hack-v5/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/app/locallib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/hisiko/hisilib:$LD_LIBRARY_PATH
export PATH=/home/app/localbin:$PATH
export PATH=/home/base/tools:$PATH

CONF_FILE="etc/system.conf"
YI_HACK_V5_PREFIX="/tmp/sd/yi-hack-v5"

get_config()
{
	key=$1
	grep $1 $YI_HACK_V5_PREFIX/$CONF_FILE | cut -d "=" -f2
}

if [ -d "/tmp/sd/yi-hack-v5" ] ; then                
(
if [[ $(get_config PROXYCHAINSNG) == "yes" ]] ; then
	$YI_HACK_V5_PREFIX/bin/proxychains4 ./cloudAPI_real "$@"
else
	./cloudAPI_real "$@"
fi
)

else
    ./cloudAPI_real "$@"
fi
